# Generated by Django 4.1.7 on 2023-04-02 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40, unique=True)),
                ('detalle', models.CharField(max_length=40)),
                ('descripcion', models.TextField()),
                ('comentario', models.TextField()),
            ],
            options={
                'db_table': 'Blogs',
            },
        ),
    ]
