# Generated by Django 4.1.7 on 2023-04-05 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyectoFinal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogsmodel',
            name='autor',
            field=models.CharField(default=0, max_length=40, unique=True),
            preserve_default=False,
        ),
    ]
