# Generated by Django 4.1.7 on 2023-04-05 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyectoFinal', '0002_blogsmodel_autor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogsmodel',
            old_name='autor',
            new_name='usuario',
        ),
    ]
